
name: Test commit
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Test Contract
        uses: actions/setup-node@v2.1.5
        run: cd contract && npx hardhat test
